name: SkyPrisonCore
authors: [Redhelmet8, DrakePork]
description: Guard plugins for SkyPrison
version: 3.0
main: net.skyprison.Main.SkyPrisonMain
api-version: 1.15
website: https://skyprison.net
depend: [WorldGuard, WorldEdit, PlaceholderAPI, VotingPlugin]
commands:
  #
  # Guard Commands
  #
  contraband:
    description: Request contraband from player
    usage: /<command>
    aliases: cb
    permission: skyprisoncore.guard.contraband
    permission-message: §4Error:§c You do not have permission to execute this command...
  guardduty:
    description: Go on and off duty as a guard
    usage: /<command>
    permission: skyprisoncore.guard.guardduty
    permission-message: §4Error:§c You do not have permission to execute this command...
  g:
    description: Guard Chat
    usage: /<command>
    permission: skyprisoncore.guard.guardchat
    permission-message: §4Error:§c You do not have permission to execute this command...
  # Builder Commands
  buildmode:
    description: Go on and off builder mode
    usage: /<command>
    permission: skyprisoncore.builder.buildmode
    permission-message: §4Error:§c You do not have permission to execute this command...
  b:
    description: Builder Chat
    usage: /<command>
    permission: skyprisoncore.builder.buildchat
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Minigame Commands
  #
  spongeloc:
    description: Sponge Commands
    usage: /<command>
    permission: skyprisoncore.sponge
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Teleport Commands
  #
  regiontp:
    description: Teleport players within regions to other places
    usage: /<command>
    permission: skyprisoncore.teleport.region
    permission-message: §4Error:§c You do not have permission to execute this command...
  minetp:
    description: Teleport with tokens wow
    usage: /<command>
    permission: skyprisoncore.teleport.token
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # GUI Commands
  #
  dropchest:
    description: DropChest Commands
    usage: /<command>
    permission: skyprisoncore.dropchest
    permission-message: §4Error:§c You do not have permission to execute this command...
  rewards:
    description: Opens the secrets GUI
    usage: /<command>
    aliases: [reward, secret, secrets]
    permission: skyprisoncore.rewardgui
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Opme Commands
  #
  opme:
    description: Ops the player.
    usage: /<command>
    permission: skyprisoncore.opme
    permission-message: §4Error:§c You do not have permission to execute this command...
  deopme:
    description: Deops the player.
    usage: /<command>
    permission: skyprisoncore.deopme
    permission-message: §4Error:§c You do not have permission to execute this command...
  op:
    description: Ops a player.
    usage: /<command>
    permission: skyprisoncore.op
    permission-message: §4Error:§c You do not have permission to execute this command...
  deop:
    description: Deops a player
    usage: /<command>
    permission: skyprisoncore.deop
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  #
  # Guard Permissions
  #
  skyprisoncore.guard.guardduty:
    description: Gives access to /guardduty
  skyprisoncore.guard.adminguard:
    description: Makes you admin guard when you do /guardduty
  skyprisoncore.guard.seniorguard:
    description: Makes you senior guard when you do /guardduty
  skyprisoncore.guard.guard:
    description: Makes you guard when you do /guardduty
  skyprisoncore.guard.trialguard:
    description: Makes you trial guard when you do /guardduty
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.guard.itembypass:
    description: Bypasses Item Removal and that kind of stuff
  skyprisoncore.guard.guardchat:
    description: Gives access to guardchat
  skyprisoncore.guard.contraband:
    description: Gives access to /cb
  #
  # Builder Permissions
  #
  skyprisoncore.builder.buildmode:
    description: Gives access to /buildmode
  skyprisoncore.builder.onduty:
    description: player is in build mode when they have this perm
    default: false
  skyprisoncore.builder.buildchat:
    description: Gives access to buildchat
  #
  # Minigame Permissions
  #
  skyprisoncore.sponge:
    description: Gives acess to /spongeloc
  #
  # Teleport Permissions
  #
  skyprisoncore.teleport.token:
    description: Gives access to /minetp
  skyprisoncore.teleport.region:
    description: Gives access to all /regiontp commands
  #
  # GUI Permissions
  #
  skyprisoncore.rewardgui:
    description: Gives access to /rewards
  skyprisoncore.dropchest:
    description: Gives access to /dropchest
  #
  # Opme Permissions
  #
  skyprisoncore.op:
    description: Gives access to op command
    default: false
  skyprisoncore.deopme:
    description: Gives access to deopme command
    default: false
  skyprisoncore.opme:
    description: Gives access to opme command
    default: false
  skyprisoncore.deop:
    description: Gives access to deop command
    default: false
  skyprisoncore.deop.joinbypass:
    description: Bypasses deop on join
    default: false
  skyprisoncore.opme.*:
    description: Gives access to all opme commands
    default: false
    children:
      opme.opme: true
      opme.op: true
      opme.deop: true
      opme.deopme: true
      opme.joinbypass: true
