name: SkyPrisonCore
authors: [DrakePork, Redhelmet8]
description: All the Custom Stuffs for SkyPrison
version: ${project.version}
main: com.github.drakepork.skyprisoncore.Core
api-version: 1.16
website: https://skyprison.net/
depend: [WorldGuard, WorldEdit, PlaceholderAPI, VotingPlugin, CMI, BKCommonLib, DiscordSRV, Parkour]
commands:
  test:
    description: Go on and off duty as a guard
    usage: /<command>
    permission: skyprisoncore.command.econcheck
    permission-message: §4Error:§c You do not have permission to execute this command...
  econcheck:
    description: Check the state of the economy
    usage: /<command>
    permission: skyprisoncore.command.econcheck
    permission-message: §4Error:§c You do not have permission to execute this command...
  ignoretp:
    description: Ignore someones tpa requests
    aliases: [tpignore]
    usage: /<command>
    permission: skyprisoncore.command.ignoretp
    permission-message: §4Error:§c You do not have permission to execute this command...
  bartender:
    description: Opens bartender GUI
    usage: /<command>
    permission: skyprisoncore.command.bartender
    permission-message: §4Error:§c You do not have permission to execute this command...
  safezone:
    description: Gives a player a safezone warning
    usage: /<command>
    permission: skyprisoncore.command.safezone
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Contraband Commands
  #
  sword:
    description: Request sword from player
    usage: /<command>
    permission: skyprisoncore.command.sword
    permission-message: §4Error:§c You do not have permission to execute this command...
  bow:
    description: Request bow from player
    usage: /<command>
    permission: skyprisoncore.command.bow
    permission-message: §4Error:§c You do not have permission to execute this command...
  contraband:
    description: Request contraband from player
    usage: /<command>
    permission: skyprisoncore.command.contraband
    permission-message: §4Error:§c You do not have permission to execute this command...
  guardduty:
    description: Enable/disable guardduty
    usage: /<command>
    permission: skyprisoncore.command.guardduty
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Minigame Commands
  #
  spongeloc:
    description: Sponge Commands
    usage: /<command>
    permission: skyprisoncore.command.sponge
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Teleport Commands
  #
  tokenteleport:
    description: Teleport with tokens wow
    aliases: [tokentp]
    usage: /<command>
    permission: skyprisoncore.command.token
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # GUI Commands
  #
  dropchest:
    description: DropChest Commands
    usage: /<command>
    permission: skyprisoncore.command.dropchest
    permission-message: §4Error:§c You do not have permission to execute this command...
  rewards:
    description: Opens the secrets GUI
    usage: /<command>
    aliases: [reward, secret, secrets]
    permission: skyprisoncore.command.secrets
    permission-message: §4Error:§c You do not have permission to execute this command...
  secretfound:
    description: Adds secretfound
    usage: /<command>
    permission: skyprisoncore.command.secretfound
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Bounty Commands
  #
  bounty:
    description: Bounty Commands
    usage: /<command>
    permission: skyprisoncore.command.bounty
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Donation Commands
  #
  donorbulk:
    description: Add a donation
    usage: /<command>
    permission: skyprisoncore.command.donorbulk
    permission-message: §4Error:§c You do not have permission to execute this command...
  donoradd:
    description: Add a donation
    usage: /<command>
    permission: skyprisoncore.command.donoradd
    permission-message: §4Error:§c You do not have permission to execute this command...
  purchases:
    description: Show purchases
    usage: /<command>
    permission: skyprisoncore.command.purchases
    permission-message: §4Error:§c You do not have permission to execute this command...
  donorcheck:
    description: Check the state of the economy
    usage: /<command>
    permission: skyprisoncore.command.donorcheck
    permission-message: §4Error:§c You do not have permission to execute this command...
  endupgrade:
    description: Opens the end upgrade GUI
    usage: /<command>
    permission: skyprisoncore.command.endupgrade
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Killinfo Commands
  #
  killinfo:
    description: Shows info about PvP
    usage: /<command>
    aliases: [killsinfo, killstats, pvpstats]
    permission: skyprisoncore.command.killinfo
    permission-message: §4Error:§c You do not have permission to execute this command...

  dontsell:
    description: Adds/removes an item from the dont sell list
    usage: /<command>
    permission: skyprisoncore.command.dontsell
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Cheese?
  #
  referral:
    description: Give tokens to the guy who refered you to the server
    usage: /<command>
    aliases: [refer]
    permission: skyprisoncore.command.referral
    permission-message: §4Error:§c You do not have permission to execute this command...
  referrallist:
    description: See everyone who has referred you
    usage: /<command>
    aliases: [referlist, reflist]
    permission: skyprisoncore.command.referrallist
    permission-message: §4Error:§c You do not have permission to execute this command...


  firstjointop:
    description: See everyone who has referred you
    usage: /<command>
    aliases: [referlist, reflist]
    permission: skyprisoncore.command.firstjointop
    permission-message: §4Error:§c You do not have permission to execute this command...
  permshop:
    description: See everyone who has referred you
    usage: /<command>
    aliases: [referlist, reflist]
    permission: skyprisoncore.command.permshop
    permission-message: §4Error:§c You do not have permission to execute this command...
  buyback:
    description: Buyback items you sold
    usage: /<command>
    permission: skyprisoncore.command.buyback
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  #
  # Guard Permissions
  #
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.contraband.itembypass:
    description: Bypasses Item Removal and that kind of stuff
  #
  # Contraband Permissions
  #
  skyprisoncore.command.sword:
    description: Gives access to /sword
  skyprisoncore.command.bow:
    description: Gives access to /bow
  skyprisoncore.command.contraband:
    description: Gives access to /contraband
  skyprisoncore.command.safezone:
    description: Gives access to /safezone

  skyprisoncore.command.guardduty:
    description: Gives access to /guardduty
  #
  # Builder Permissions
  #
  skyprisoncore.builder.onduty:
    description: player is in build mode when they have this perm
    default: false
  #
  # Minigame Permissions
  #
  skyprisoncore.command.sponge:
    description: Gives acess to /spongeloc
  #
  # Teleport Permissions
  #
  skyprisoncore.command.token:
    description: Gives access to /tokenteleport
  #
  # GUI Permissions
  #
  skyprisoncore.command.secretfound:
    description: Gives access to /secrets
  skyprisoncore.command.secrets:
    description: Gives access to /secrets
  skyprisoncore.command.dropchest:
    description: Gives access to /dropchest
  #
  # Bounty Permissions
  #
  skyprisoncore.command.bounty:
    description: Gives access to /bounty commands
  skyprisoncore.command.bounty.bypass:
    description: Players cant bounty you.
  skyprisoncore.command.bounty.silent:
    description: Hides bounty messages
    default: false
  #
  # Donation Permissions
  #
  skyprisoncore.command.donorbulk:
    description: Gives you access to /donorbulk
  skyprisoncore.command.donoradd:
    description: Gives you access to /donoradd
  skyprisoncore.command.purchases:
    description: Gives you access to /purchases
  skyprisoncore.command.donorcheck:
    description: Gives you access to /purchases
  #
  # Killinfo Permissions
  #
  skyprisoncore.command.killinfo:
    description: Gives access to /killinfo
  #
  # Referral
  #
  skyprisoncore.command.referrallist:
    description: Gives access to /referrallist
  skyprisoncore.command.referral:
    description: Gives access to /referral

  skyprisoncore.command.firstjointop:
    description: Gives access to /referral
  skyprisoncore.command.permshop:
    description: Gives access to /referral
  skyprisoncore.command.econcheck:
    description: Gives access to /referral
  skyprisoncore.command.buyback:
    description: Gives access to /buyback
  skyprisoncore.command.bartender:
    description: Gives access to /bartender
  skyprisoncore.command.dontsell:
    description: Gives access to /dontsell
  skyprisoncore.command.endupgrade:
    description: Gives access to /endupgrade